"use client";

import { useMemo, useState } from "react";

const questions = Array.from({ length: 12 }, (_, i) => i + 1);
const students = [
  { name: "박서연", role: "설명하는 짝", color: "#dff5e9", accuracy: "92%", matched: "김민준" },
  { name: "김민준", role: "질문하는 짝", color: "#e6ebff", accuracy: "78%", matched: "박서연" },
  { name: "이준혁", role: "설명하는 짝", color: "#fff0d8", accuracy: "84%", matched: "최하늘" },
  { name: "최하늘", role: "질문하는 짝", color: "#ffe6e2", accuracy: "71%", matched: "이준혁" },
];

export default function Home() {
  const [screen, setScreen] = useState<"login" | "student" | "admin">("login");
  const [loginRole, setLoginRole] = useState<"student" | "admin">("student");
  const [answers, setAnswers] = useState<Record<number, "know" | "need">>({ 1: "know", 2: "know", 3: "know", 4: "need", 5: "know", 6: "need", 7: "know", 8: "know", 9: "need" });
  const done = Object.keys(answers).length;
  const score = useMemo(() => Math.round((Object.values(answers).filter((a) => a === "know").length / Math.max(done, 1)) * 100), [answers, done]);

  if (screen === "login") return <Login role={loginRole} setRole={setLoginRole} onLogin={() => setScreen(loginRole)} />;
  return <div className="app-shell"><aside className="sidebar"><div className="logo"><span>✦</span> 배움짝</div><div className="school-pill">2학년 3반 <span>⌄</span></div><div className="side-label">MENU</div><button className="side-link active">▦ <span>{screen === "admin" ? "학급 대시보드" : "내 배움짝"}</span></button><button className="side-link">◌ <span>{screen === "admin" ? "학생별 진단" : "오늘의 질문"}</span></button><button className="side-link">♧ <span>{screen === "admin" ? "짝 매칭 관리" : "짝 활동 기록"}</span></button><button className="side-link">⚙ <span>설정</span></button><div className="sidebar-bottom"><div className="help-box"><b>도움이 필요하신가요?</b><span>사용 가이드 보기 →</span></div><button className="profile" onClick={() => setScreen("login")}><span className="mini-avatar">{screen === "admin" ? "쌤" : "서"}</span><span><b>{screen === "admin" ? "김선생님" : "박서연"}</b><small>{screen === "admin" ? "교사 계정" : "학생 계정"}</small></span><span className="more">•••</span></button></div></aside><main className="dashboard"><header className="topbar"><div className="breadcrumb">배움짝 <span>/</span> {screen === "admin" ? "학급 대시보드" : "학생 화면"}</div><div className="top-actions"><span>◔ 알림</span><button className="role-switch" onClick={() => setScreen(screen === "admin" ? "student" : "admin")}>{screen === "admin" ? "학생 화면 보기" : "교사 화면 보기"} ↗</button></div></header>{screen === "admin" ? <Admin /> : <Student answers={answers} setAnswers={setAnswers} done={done} score={score} />}</main></div>;
}

function Login({ role, setRole, onLogin }: { role: "student" | "admin"; setRole: (r: "student" | "admin") => void; onLogin: () => void }) {
  return <main className="login-page"><div className="login-mark"><span>✦</span> 배움짝</div><div className="login-card"><div className="login-intro"><p className="overline">SMART PEER MATCHING</p><h1>함께 배우고,<br /><em>배움의 빈틈</em>을 채워요.</h1><p>우리 반 친구와 문제를 설명하고 질문하며<br />더 잘 이해하는 수학 수업을 시작해요.</p><div className="login-orb"><i /><i /><i /></div></div><div className="login-form"><h2>배움짝 시작하기</h2><p className="muted">계정 유형을 선택하고 로그인해 주세요.</p><div className="role-tabs"><button className={role === "student" ? "selected" : ""} onClick={() => setRole("student")}>학생</button><button className={role === "admin" ? "selected" : ""} onClick={() => setRole("admin")}>교사</button></div><label>{role === "student" ? "이름" : "교사 이메일"}<input placeholder={role === "student" ? "예: 박서연" : "teacher@school.kr"} defaultValue={role === "student" ? "박서연" : "teacher@school.kr"} /></label><label>{role === "student" ? "학급 코드" : "학교 코드"}<input placeholder={role === "student" ? "예: MATH-2-3" : "예: BAEM-2024"} defaultValue={role === "student" ? "MATH-2-3" : "BAEM-2024"} /></label><button className="login-button" onClick={onLogin}>{role === "student" ? "내 배움짝 확인하기" : "학급 대시보드 열기"} <span>→</span></button><p className="safe">🔒 수업 내에서만 안전하게 사용돼요.</p></div></div><p className="login-footer">배움짝은 학생 간 협력 학습을 돕는 수업용 서비스입니다.</p></main>;
}

function Student({ answers, setAnswers, done, score }: { answers: Record<number, "know" | "need">; setAnswers: React.Dispatch<React.SetStateAction<Record<number, "know" | "need">>>; done: number; score: number }) {
  const matched = students[0];
  return <><section className="welcome"><div><p className="overline">TODAY'S CHECK-IN</p><h1>박서연 님, 지금 상태를 알려주세요</h1><p>문제마다 하나를 선택하면 나에게 맞는 배움짝을 추천해 드려요.</p></div><div className="completion"><span>응답 현황 <b>{done} / 12 완료</b></span><div><i style={{ width: `${(done / 12) * 100}%` }} /></div></div></section><div className="student-grid"><section className="diagnostic panel"><div className="panel-head"><div><h2>문제마다 하나를 선택하세요</h2><p>초록은 “알고 있어요”, 빨강은 “잘 모르겠어요”를 뜻해요.</p></div><span className="score-badge">현재 이해도 <b>{score}%</b></span></div><div className="question-grid">{questions.map((q) => <div className="question" key={q}><b>{q}번 문제</b><button className={answers[q] === "know" ? "know on" : "know"} onClick={() => setAnswers((v) => ({ ...v, [q]: "know" }))}>✓ 알고 있어요</button><button className={answers[q] === "need" ? "need on" : "need"} onClick={() => setAnswers((v) => ({ ...v, [q]: "need" }))}>? 잘 모르겠어요</button></div>)}</div><div className="diagnostic-foot"><button className="primary">응답 저장하기</button><span>◷ 마지막 저장 1분 전</span></div></section><aside className="match-card"><div className="match-title">나의 배움짝 <span>✦</span></div><div className="match-people"><div><div className="person blue">민</div><b>김민준</b><small>질문하는 짝</small></div><strong>↔</strong><div><div className="person green">서</div><b>박서연</b><small>설명하는 짝</small></div></div><div className="role-note"><span>나의 역할</span><b>친구에게 설명해요</b><span>짝의 역할</span><b>모르는 것을 질문해요</b></div><div className="together"><b>함께 풀 문제</b><div><span>4번</span><span>9번</span><span>11번</span></div><p>서로 알고 있는 부분을 묻고<br />설명하며 해결해 보세요.</p></div><button className="primary full">짝 활동 시작하기 →</button></aside></div></>;
}

function Admin() { return <><section className="welcome admin-welcome"><div><p className="overline">CLASS OVERVIEW</p><h1>대단원 연습문제, 함께 해결해요</h1><p>2학년 3반 수학 · 4단원 비례식과 비례배분</p></div><button className="primary">+ 새 수업 만들기</button></section><div className="stat-grid"><div className="stat-card"><span>응답 완료율</span><b>87%</b><i className="ring blue-ring">↗</i></div><div className="stat-card"><span>답변 완료</span><b>58명</b><i className="ring green-ring">✓</i></div><div className="stat-card"><span>도움이 필요해요</span><b>38명</b><i className="ring coral-ring">?</i></div><div className="stat-card"><span>배움짝</span><b>24팀</b><i className="ring navy-ring">♟</i></div></div><div className="admin-grid"><section className="panel heatmap"><div className="panel-head"><div><h2>학생별 문제 이해도</h2><p>초록은 이해, 주황은 추가 설명이 필요한 상태예요.</p></div><button className="secondary">전체 보기 ↗</button></div><div className="heat-header"><span>학생</span>{questions.map((q) => <span key={q}>{q}</span>)}</div>{students.map((s, i) => <div className="heat-row" key={s.name}><b>{s.name}</b>{questions.map((q) => <i key={q} className={(q + i) % 4 === 0 ? "warm" : "good"}>{(q + i) % 4 === 0 ? "!" : "✓"}</i>)}</div>)}</section><section className="panel top3"><div className="panel-head"><div><h2>어려운 문제 TOP 3</h2><p>추가 설명이 필요한 문제예요.</p></div><span className="trend">이번 수업</span></div>{[{ n: 1, q: "9번 문제", p: 43 }, { n: 2, q: "4번 문제", p: 38 }, { n: 3, q: "11번 문제", p: 31 }].map((x) => <div className="top-row" key={x.n}><strong>{x.n}</strong><div><b>{x.q}</b><div><i style={{ width: `${x.p * 1.8}%` }} /></div></div><span>{x.p}%</span></div>)}</section></div><section className="panel pair-panel"><div className="panel-head"><div><h2>배움짝 매칭 결과</h2><p>알고 있는 학생과 도움이 필요한 학생을 연결했어요.</p></div><button className="secondary">매칭 다시 하기 ↻</button></div><div className="pair-grid">{students.map((s) => <div className="pair-row" key={s.name}><div className="person" style={{ background: s.color }}>{s.name.slice(0, 1)}</div><b>{s.name}</b><span>↔</span><div className="person light">{s.matched.slice(0, 1)}</div><b>{s.matched}</b><small>{s.role}</small><button className="ghost">상세 보기 →</button></div>)}</div></section></>; }
